# System
dir0 = /lib:ro
dir1 = /lib64:ro
dir2 = /usr/lib:ro
dir3 = /etc/ld.so.cache:ro

# Runtime
dir4 = /usr/bin:ro
dir5 = /bin:ro
dir6 = /usr/lib/jvm/java-21-openjdk-amd64:ro
dir7 = /etc/java-21-openjdk:ro

# Config
dir8 = /etc/alternatives:ro
dir9 = /etc/ssl/certs:ro
dir10 = /etc/localtime:ro

# Writeable
dir11 = /dev/urandom:rw
