box_root = /var/lib/isolate

# Core System
dir0 = /lib:ro
dir1 = /lib64:ro
dir2 = /usr/lib:ro
dir3 = /etc/ld.so.cache:ro

# Binaries
dir4 = /usr/bin:ro
dir5 = /bin:ro
dir6 = /sbin:ro

# Java Fix need the entire JVM directory and all of /etc
dir7 = /usr/lib/jvm:ro
dir8 = /etc:ro

# Requirements for Python/Node/Java
dir9 = /usr/share:ro
dir10 = /var/lib:ro

# Essential Devices
dir11 = /dev/urandom:rw
dir12 = /dev/null:rw
dir13 = /dev/zero:rw